### PR TITLE
Upgrade LVL to AGP 8.1.4.

### PR DESCRIPTION
**Pull request by KhaledHelmy**
Upgrade the licensing library to be compatible with Gradle 8.2 and AGP 8.1.4.

### CODE REVIEW

**Review by mdc-lon — APPROVED** [review]
LGTM

**Comment by splendapps** [comment]
I have build.gradle with this line:
implementation 'com.github.google:play-licensing:-SNAPSHOT'
and got an error:
Failed to resolve: com.github.google:play-licensing:-SNAPSHOT

This entry will no longer be shared?
I implemented licensing to join Google Play Pass. Now we can't build packages.
Can you give a quick answer on what to do next?

**Comment by KhaledHelmy** [comment]
@splendapps The library is not published with Gradle. You can refer to https://developer.android.com/google/play/licensing for a guide on how to integrate and customize the license check in your app.

For further problems, please file a separate issue which would make it easier to contain the relevant information necessary for troubleshooting the problem. Thank you!

**Comment by DavidPDev** [comment]
@splendapps Did you figure how to make it work using the line
implementation 'com.github.google:play-licensing:-SNAPSHOT'
?
Thank you.

**Comment by splendapps** [comment]
Yes, thanks! Everything work well!

**Comment by DavidPDev** [comment]
> Yes, thanks! Everything work well!

Thank you for your reply, but, what changes have you made?
Still using the 

`implementation 'com.github.google:play-licensing:-SNAPSHOT'`

line?

**Comment by splendapps** [comment]
No, just implemented licensing it in the following method you recommended:
https://developer.android.com/google/play/licensing/setting-up

**Comment by DavidPDev** [comment]
@KhaledHelmy Please, I have created a new ( #10 ) issue!
Thank you!

**Pull request merged**
