### PR TITLE
[BUGFIX] Oneway keyword

### PR DESCRIPTION
**Pull request by pfaffenrodt**
- [TASK] update gradle
- [BUGFIX] oneway keyword has been moved to method level

### CODE REVIEW

**Comment by pfaffenrodt** [comment]
I signed it!

**Comment by tjohns** [comment]
Hello, thanks for the contribution.

Do you have a reference to where this change took place? I can't find it in the Android docs, and the current implementation isn't raising any warnings in my build.

**Comment by pfaffenrodt** [comment]
The "oneway" keyword has been moved to the method level.

Android Studio tells me, that there is an error.
"< interface declaration >, < parcelable declaration > or AidlTokenType.import expected, got 'oneway'"

So moving the keyword to method level has fixed it for me.

I also don't found any reference in the docs. The only reference I found was on stackoverflow https://stackoverflow.com/questions/38632897/aidl-oneway-keyword-error

**Comment by Kisty** [comment]
Here's the documentation reference: 

_The oneway keyword modifies the behavior of remote calls. When it is used, a remote call does not block. It sends the transaction data and immediately returns. The implementation of the interface eventually receives this as a regular call from the [Binder](https://developer.android.com/reference/android/os/Binder) thread pool as a normal remote call. If oneway is used with a local call, there is no impact, and the call is still synchronous._
https://developer.android.com/guide/components/aidl

I think this changes it from a synchronous call to an asynchronous one-shot call, but since the AIDL already has that `oneway` keyword, then this shouldn't pose an issue. 

I do note that the interface method name has changed from: `verifyLicense` to `checkLicense`. Is this intended? Wouldn't it be a breaking change if so?

This PR might be obselete

**Comment by pfaffenrodt** [comment]
This thing is so old. I dont even remember the pupose of this lib. 

Opinion: Lets create a bunch of libs unmaintained. make it open source. So it will receive PRs. Oh no one review them.

**Pull request closed without merging**
